### ISSUE TITLE
CentOS7 On virtualbox

### ISSUE THREAD

**Issue by stephenrlouie** [gemini-project/gemini#28]
firewalld does not start by default using the centos 7 [image] (https://atlas.hashicorp.com/geerlingguy/boxes/centos7)

Work around:
```
sudo yum install python-pip -y 
sudo pip install decorator
systemctl start firewalld.service
```

**Comment by danehans** [comment]
The decorator is required to start firewalld?

**Comment by danehans** [comment]
I noticed firewalld does not start in conrtib vagrant too, so I'm not worried about gem vagrant using firewalld. The contrib ansible code ignores firewalld/iptables errors, so we should be covered:

https://github.com/kubernetes/contrib/blob/master/ansible/roles/flannel/tasks/firewalld.yml#L5

I will close this issue unless I hear otherwise.

**Comment by stephenrlouie** [comment]
This issue should still remain open, gemini/vagrant is on centos6.7 right now. I created this issue to track the update to using Cent7

**Comment by danehans** [comment]
Sounds like a plan.

**Comment by stephenrlouie** [comment]
I'll focus on bringing our virtualenv up to cent7 now, I wrote down the modifications I needed to make it work.

**Comment by danehans** [comment]
Thx!

**Comment by danehans** [comment]
Closing due to PR #41
